config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'
  resources :profiles
  resources :agc_definition_tables
  devise_for :users
  resources :iress_portfolio_cash_details
  resources :year_to_dates
  resources :month_to_dates 
  resources :profit_and_losses do
    collection do
      get :get_pnl_details
      post :get_profit_and_loss_by_fund_account
    end
  end
  resources :turnovers
  resources :prices
  resources :portfolio_valuations do
    collection do
    post :get_portfoilio_valuation_details  
    post :get_report_graph_portfolio_valuations
    get :get_portfoilio_graph_details
    end
  end
  resources :instruments
  resources :instrument_margin_levels
  resources :fx_rates
  resources :deal_transactions
  resources :client_informations
  resources :client_category_to_instruments
  resources :client_categories
  resources :cash_flow_types
  resources :cash_flow_sub_types
  resources :financial_transactions do
    collection do 
      post :get_ft_by_fund_account_and_date
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash_flow_sub_type.rb
class CashFlowSubType < ApplicationRecord
    self.table_name = "peregrine.cash_flow_sub_type"

end

app/models/cash_flow_type.rb
class CashFlowType < ApplicationRecord
    self.table_name = "peregrine.cash_flow_type"
end

app/models/client_category.rb
class ClientCategory < ApplicationRecord
    self.table_name = "peregrine.client_category"
end

app/models/client_information.rb
class ClientInformation < ApplicationRecord
    self.table_name = "peregrine.client_category_information"
end

app/models/deal_transaction.rb
class DealTransaction < ApplicationRecord
    self.table_name = "peregrine.deal_transaction"
end

app/models/fx_rate.rb
class FxRate < ApplicationRecord
    self.table_name = "peregrine.fx_rate"
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    self.table_name = "peregrine.instrument"
end

app/models/month_to_date.rb
class MonthToDate < ApplicationRecord
  self.table_name = "peregrine.func_month_to_date"


  def self.get_all_month_to_date(accounts)

    all_dates = []
    MonthToDate.where(fund_account: accounts).each{|m| all_dates << m.date.strftime("%Y%m") }
    date = all_dates.uniq

    mtd_date_data = {}
    date.each{|d| mtd_date_data[d] = []} 

    mtd_date_data.each do |k, v|
      MonthToDate.where(fund_account: accounts).all.each do |ft|
        if (ft.date.strftime("%Y%m").to_i - k.to_i) == 0
          v << ft.as_json
        end
      end
    end

    # mtd_date_data.each do |k, v|
    #   FinancialTransaction.where(fund_account: accounts).all.each do |ft|
    #     if (ft.value_date.strftime("%Y%m").to_i - k.to_i) == 0
    #       v << ft.as_json
    #     end
    #   end
    # end
  end
    
end

app/models/price.rb
class Price < ApplicationRecord
    self.table_name = "peregrine.price"
end

app/models/profile.rb
class Profile < ApplicationRecord

  def self.get_profit_and_loss_by_user_id(user_id)
    list_fund_accounts = []
    user = User.find(user_id)
    user.agc_definition_tables.map{|x| list_fund_accounts << x.fund_account}
    profit_and_loss = []
    list_fund_accounts.each do |fa|
      profit_and_loss = ProfitAndLoss.all.where(fund_account: fa)
    end
    profit_and_loss
  end

  def self.get_user_fund_accounts(user_id)
    list_fund_accounts = []
    user = User.find(user_id)
    user.agc_definition_tables.map{|x| list_fund_accounts << x.fund_account}

    list_fund_accounts.uniq
  end

end

app/models/profit_and_loss.rb
class ProfitAndLoss < ApplicationRecord
  self.table_name = "peregrine.func_profit_and_loss"


  def self.get_profit_and_loss_by_account(user_fund_accounts)
    return ProfitAndLoss.all.where(fund_account: user_fund_accounts)
  end  

end

app/models/turnover.rb
class Turnover < ApplicationRecord
    self.table_name = "peregrine.turnover"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :agc_definition_tables

end

app/models/year_to_date.rb
class YearToDate < ApplicationRecord
    self.table_name = "peregrine.func_year_to_date"
end

app/controllers/client_categories_controller.rb
class ClientCategoriesController < ApplicationController
  before_action :set_client_category, only: [:show, :edit, :update, :destroy]

  # GET /client_categories
  # GET /client_categories.json
  def index
    @client_categories = ClientCategory.all
  end

  # GET /client_categories/1
  # GET /client_categories/1.json
  def show
  end

  # GET /client_categories/new
  def new
    @client_category = ClientCategory.new
  end

  # GET /client_categories/1/edit
  def edit
  end

  # POST /client_categories
  # POST /client_categories.json
  def create
    @client_category = ClientCategory.new(client_category_params)

    respond_to do |format|
      if @client_category.save
        format.html { redirect_to @client_category, notice: 'Client category was successfully created.' }
        format.json { render :show, status: :created, location: @client_category }
      else
        format.html { render :new }
        format.json { render json: @client_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_categories/1
  # PATCH/PUT /client_categories/1.json
  def update
    respond_to do |format|
      if @client_category.update(client_category_params)
        format.html { redirect_to @client_category, notice: 'Client category was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_category }
      else
        format.html { render :edit }
        format.json { render json: @client_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_categories/1
  # DELETE /client_categories/1.json
  def destroy
    @client_category.destroy
    respond_to do |format|
      format.html { redirect_to client_categories_url, notice: 'Client category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_category
      @client_category = ClientCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_category_params
      params.require(:client_category).permit(:fund_account, :client_category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/client_categories_helper.rb
module ClientCategoriesHelper
end

app/helpers/fx_rates_helper.rb
module FxRatesHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/turnovers_helper.rb
module TurnoversHelper
end

app/views/client_categories/_form.html.erb
<%= form_with(model: client_category, local: true) do |form| %>
  <% if client_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_category.errors.count, "error") %> prohibited this client_category from being saved:</h2>

      <ul>
      <% client_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fund_account %>
    <%= form.number_field :fund_account %>
  </div>

  <div class="field">
    <%= form.label :client_category %>
    <%= form.text_field :client_category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/client_categories/edit.html.erb
<h1>Editing Client Category</h1>

<%= render 'form', client_category: @client_category %>

<%= link_to 'Show', @client_category %> |
<%= link_to 'Back', client_categories_path %>

app/views/client_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Categories</h1>

<table>
  <thead>
    <tr>
      <th>Fund account</th>
      <th>Client category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_categories.each do |client_category| %>
      <tr>
        <td><%= client_category.fund_account %></td>
        <td><%= client_category.client_category %></td>
        <td><%= link_to 'Show', client_category %></td>
        <td><%= link_to 'Edit', edit_client_category_path(client_category) %></td>
        <td><%= link_to 'Destroy', client_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Category', new_client_category_path %>

app/views/client_categories/new.html.erb
<h1>New Client Category</h1>

<%= render 'form', client_category: @client_category %>

<%= link_to 'Back', client_categories_path %>

app/views/client_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fund account:</strong>
  <%= @client_category.fund_account %>
</p>

<p>
  <strong>Client category:</strong>
  <%= @client_category.client_category %>
</p>

<%= link_to 'Edit', edit_client_category_path(@client_category) %> |
<%= link_to 'Back', client_categories_path %>