config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'
  resources :profiles
  resources :agc_definition_tables
  devise_for :users
  resources :iress_portfolio_cash_details
  resources :year_to_dates
  resources :month_to_dates 
  resources :profit_and_losses do
    collection do
      get :get_pnl_details
      post :get_profit_and_loss_by_fund_account
    end
  end
  resources :turnovers
  resources :prices
  resources :portfolio_valuations do
    collection do
    post :get_portfoilio_valuation_details  
    post :get_report_graph_portfolio_valuations
    get :get_portfoilio_graph_details
    end
  end
  resources :instruments
  resources :instrument_margin_levels
  resources :fx_rates
  resources :deal_transactions
  resources :client_informations
  resources :client_category_to_instruments
  resources :client_categories
  resources :cash_flow_types
  resources :cash_flow_sub_types
  resources :financial_transactions do
    collection do 
      post :get_ft_by_fund_account_and_date
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/turnover.rb
class Turnover < ApplicationRecord
    self.table_name = "peregrine.turnover"
end

app/controllers/turnovers_controller.rb
class TurnoversController < ApplicationController
  before_action :set_turnover, only: [:show, :edit, :update, :destroy]

  # GET /turnovers
  # GET /turnovers.json
  def index
    @turnovers = Turnover.all
  end

  # GET /turnovers/1
  # GET /turnovers/1.json
  def show
  end

  # GET /turnovers/new
  def new
    @turnover = Turnover.new
  end

  # GET /turnovers/1/edit
  def edit
  end

  # POST /turnovers
  # POST /turnovers.json
  def create
    @turnover = Turnover.new(turnover_params)

    respond_to do |format|
      if @turnover.save
        format.html { redirect_to @turnover, notice: 'Turnover was successfully created.' }
        format.json { render :show, status: :created, location: @turnover }
      else
        format.html { render :new }
        format.json { render json: @turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnovers/1
  # PATCH/PUT /turnovers/1.json
  def update
    respond_to do |format|
      if @turnover.update(turnover_params)
        format.html { redirect_to @turnover, notice: 'Turnover was successfully updated.' }
        format.json { render :show, status: :ok, location: @turnover }
      else
        format.html { render :edit }
        format.json { render json: @turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnovers/1
  # DELETE /turnovers/1.json
  def destroy
    @turnover.destroy
    respond_to do |format|
      format.html { redirect_to turnovers_url, notice: 'Turnover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turnover
      @turnover = Turnover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turnover_params
      params.require(:turnover).permit(:year, :month, :amount)
    end
end

app/helpers/turnovers_helper.rb
module TurnoversHelper
end

app/views/turnovers/_form.html.erb
<%= form_with(model: turnover, local: true) do |form| %>
  <% if turnover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turnover.errors.count, "error") %> prohibited this turnover from being saved:</h2>

      <ul>
      <% turnover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.number_field :month %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turnovers/edit.html.erb
<h1>Editing Turnover</h1>

<%= render 'form', turnover: @turnover %>

<%= link_to 'Show', @turnover %> |
<%= link_to 'Back', turnovers_path %>

app/views/turnovers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turnovers</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Month</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnovers.each do |turnover| %>
      <tr>
        <td><%= turnover.year %></td>
        <td><%= turnover.month %></td>
        <td><%= turnover.amount %></td>
        <td><%= link_to 'Show', turnover %></td>
        <td><%= link_to 'Edit', edit_turnover_path(turnover) %></td>
        <td><%= link_to 'Destroy', turnover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turnover', new_turnover_path %>

app/views/turnovers/new.html.erb
<h1>New Turnover</h1>

<%= render 'form', turnover: @turnover %>

<%= link_to 'Back', turnovers_path %>

app/views/turnovers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @turnover.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @turnover.month %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @turnover.amount %>
</p>

<%= link_to 'Edit', edit_turnover_path(@turnover) %> |
<%= link_to 'Back', turnovers_path %>