config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'
  resources :profiles
  resources :agc_definition_tables
  devise_for :users
  resources :iress_portfolio_cash_details
  resources :year_to_dates
  resources :month_to_dates 
  resources :profit_and_losses do
    collection do
      get :get_pnl_details
      post :get_profit_and_loss_by_fund_account
    end
  end
  resources :turnovers
  resources :prices
  resources :portfolio_valuations do
    collection do
    post :get_portfoilio_valuation_details  
    post :get_report_graph_portfolio_valuations
    get :get_portfoilio_graph_details
    end
  end
  resources :instruments
  resources :instrument_margin_levels
  resources :fx_rates
  resources :deal_transactions
  resources :client_informations
  resources :client_category_to_instruments
  resources :client_categories
  resources :cash_flow_types
  resources :cash_flow_sub_types
  resources :financial_transactions do
    collection do 
      post :get_ft_by_fund_account_and_date
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash_flow_sub_type.rb
class CashFlowSubType < ApplicationRecord
    self.table_name = "peregrine.cash_flow_sub_type"

end

app/models/cash_flow_type.rb
class CashFlowType < ApplicationRecord
    self.table_name = "peregrine.cash_flow_type"
end

app/models/client_category.rb
class ClientCategory < ApplicationRecord
    self.table_name = "peregrine.client_category"
end

app/models/client_information.rb
class ClientInformation < ApplicationRecord
    self.table_name = "peregrine.client_category_information"
end

app/models/deal_transaction.rb
class DealTransaction < ApplicationRecord
    self.table_name = "peregrine.deal_transaction"
end

app/models/fx_rate.rb
class FxRate < ApplicationRecord
    self.table_name = "peregrine.fx_rate"
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    self.table_name = "peregrine.instrument"
end

app/models/month_to_date.rb
class MonthToDate < ApplicationRecord
  self.table_name = "peregrine.func_month_to_date"


  def self.get_all_month_to_date(accounts)

    all_dates = []
    MonthToDate.where(fund_account: accounts).each{|m| all_dates << m.date.strftime("%Y%m") }
    date = all_dates.uniq

    mtd_date_data = {}
    date.each{|d| mtd_date_data[d] = []} 

    mtd_date_data.each do |k, v|
      MonthToDate.where(fund_account: accounts).all.each do |ft|
        if (ft.date.strftime("%Y%m").to_i - k.to_i) == 0
          v << ft.as_json
        end
      end
    end

    # mtd_date_data.each do |k, v|
    #   FinancialTransaction.where(fund_account: accounts).all.each do |ft|
    #     if (ft.value_date.strftime("%Y%m").to_i - k.to_i) == 0
    #       v << ft.as_json
    #     end
    #   end
    # end
  end
    
end

app/models/price.rb
class Price < ApplicationRecord
    self.table_name = "peregrine.price"
end

app/models/profile.rb
class Profile < ApplicationRecord

  def self.get_profit_and_loss_by_user_id(user_id)
    list_fund_accounts = []
    user = User.find(user_id)
    user.agc_definition_tables.map{|x| list_fund_accounts << x.fund_account}
    profit_and_loss = []
    list_fund_accounts.each do |fa|
      profit_and_loss = ProfitAndLoss.all.where(fund_account: fa)
    end
    profit_and_loss
  end

  def self.get_user_fund_accounts(user_id)
    list_fund_accounts = []
    user = User.find(user_id)
    user.agc_definition_tables.map{|x| list_fund_accounts << x.fund_account}

    list_fund_accounts.uniq
  end

end

app/models/profit_and_loss.rb
class ProfitAndLoss < ApplicationRecord
  self.table_name = "peregrine.func_profit_and_loss"


  def self.get_profit_and_loss_by_account(user_fund_accounts)
    return ProfitAndLoss.all.where(fund_account: user_fund_accounts)
  end  

end

app/models/turnover.rb
class Turnover < ApplicationRecord
    self.table_name = "peregrine.turnover"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :agc_definition_tables

end

app/models/year_to_date.rb
class YearToDate < ApplicationRecord
    self.table_name = "peregrine.func_year_to_date"
end

app/controllers/client_informations_controller.rb
class ClientInformationsController < ApplicationController
  before_action :set_client_information, only: [:show, :edit, :update, :destroy]

  # GET /client_informations
  # GET /client_informations.json
  def index
    @client_informations = ClientInformation.all
  end

  # GET /client_informations/1
  # GET /client_informations/1.json
  def show
  end

  # GET /client_informations/new
  def new
    @client_information = ClientInformation.new
  end

  # GET /client_informations/1/edit
  def edit
  end

  # POST /client_informations
  # POST /client_informations.json
  def create
    @client_information = ClientInformation.new(client_information_params)

    respond_to do |format|
      if @client_information.save
        format.html { redirect_to @client_information, notice: 'Client information was successfully created.' }
        format.json { render :show, status: :created, location: @client_information }
      else
        format.html { render :new }
        format.json { render json: @client_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_informations/1
  # PATCH/PUT /client_informations/1.json
  def update
    respond_to do |format|
      if @client_information.update(client_information_params)
        format.html { redirect_to @client_information, notice: 'Client information was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_information }
      else
        format.html { render :edit }
        format.json { render json: @client_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_informations/1
  # DELETE /client_informations/1.json
  def destroy
    @client_information.destroy
    respond_to do |format|
      format.html { redirect_to client_informations_url, notice: 'Client information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_information
      @client_information = ClientInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_information_params
      params.require(:client_information).permit(:fund_account, :fund_name, :bda_branch_code, :take_on_date, :client_title, :client_initials, :first_name, :client_surname, :idno, :tel_no_1, :tel_no_2, :email_address, :tax_no, :vat_no, :address_line1, :address_line2, :address_line3, :address_line4, :postal, :external_trading_account, :cgt_individual)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/client_informations_helper.rb
module ClientInformationsHelper
end

app/helpers/fx_rates_helper.rb
module FxRatesHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/turnovers_helper.rb
module TurnoversHelper
end

app/views/client_informations/_form.html.erb
<%= form_with(model: client_information, local: true) do |form| %>
  <% if client_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_information.errors.count, "error") %> prohibited this client_information from being saved:</h2>

      <ul>
      <% client_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fund_account %>
    <%= form.number_field :fund_account %>
  </div>

  <div class="field">
    <%= form.label :fund_name %>
    <%= form.text_field :fund_name %>
  </div>

  <div class="field">
    <%= form.label :bda_branch_code %>
    <%= form.text_field :bda_branch_code %>
  </div>

  <div class="field">
    <%= form.label :take_on_date %>
    <%= form.datetime_select :take_on_date %>
  </div>

  <div class="field">
    <%= form.label :client_title %>
    <%= form.text_field :client_title %>
  </div>

  <div class="field">
    <%= form.label :client_initials %>
    <%= form.text_field :client_initials %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :client_surname %>
    <%= form.text_field :client_surname %>
  </div>

  <div class="field">
    <%= form.label :idno %>
    <%= form.text_field :idno %>
  </div>

  <div class="field">
    <%= form.label :tel_no_1 %>
    <%= form.text_field :tel_no_1 %>
  </div>

  <div class="field">
    <%= form.label :tel_no_2 %>
    <%= form.text_field :tel_no_2 %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address %>
  </div>

  <div class="field">
    <%= form.label :tax_no %>
    <%= form.number_field :tax_no %>
  </div>

  <div class="field">
    <%= form.label :vat_no %>
    <%= form.number_field :vat_no %>
  </div>

  <div class="field">
    <%= form.label :address_line1 %>
    <%= form.text_field :address_line1 %>
  </div>

  <div class="field">
    <%= form.label :address_line2 %>
    <%= form.text_field :address_line2 %>
  </div>

  <div class="field">
    <%= form.label :address_line3 %>
    <%= form.text_field :address_line3 %>
  </div>

  <div class="field">
    <%= form.label :address_line4 %>
    <%= form.text_field :address_line4 %>
  </div>

  <div class="field">
    <%= form.label :postal %>
    <%= form.number_field :postal %>
  </div>

  <div class="field">
    <%= form.label :external_trading_account %>
    <%= form.text_field :external_trading_account %>
  </div>

  <div class="field">
    <%= form.label :cgt_individual %>
    <%= form.check_box :cgt_individual %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/client_informations/edit.html.erb
<h1>Editing Client Information</h1>

<%= render 'form', client_information: @client_information %>

<%= link_to 'Show', @client_information %> |
<%= link_to 'Back', client_informations_path %>

app/views/client_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Informations</h1>

<table>
  <thead>
    <tr>
      <th>Fund account</th>
      <th>Fund name</th>
      <th>Bda branch code</th>
      <th>Take on date</th>
      <th>Client title</th>
      <th>Client initials</th>
      <th>First name</th>
      <th>Client surname</th>
      <th>Idno</th>
      <th>Tel no 1</th>
      <th>Tel no 2</th>
      <th>Email address</th>
      <th>Tax no</th>
      <th>Vat no</th>
      <th>Address line1</th>
      <th>Address line2</th>
      <th>Address line3</th>
      <th>Address line4</th>
      <th>Postal</th>
      <th>External trading account</th>
      <th>Cgt individual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_informations.each do |client_information| %>
      <tr>
        <td><%= client_information.fund_account %></td>
        <td><%= client_information.fund_name %></td>
        <td><%= client_information.bda_branch_code %></td>
        <td><%= client_information.take_on_date %></td>
        <td><%= client_information.client_title %></td>
        <td><%= client_information.client_initials %></td>
        <td><%= client_information.first_name %></td>
        <td><%= client_information.client_surname %></td>
        <td><%= client_information.idno %></td>
        <td><%= client_information.tel_no_1 %></td>
        <td><%= client_information.tel_no_2 %></td>
        <td><%= client_information.email_address %></td>
        <td><%= client_information.tax_no %></td>
        <td><%= client_information.vat_no %></td>
        <td><%= client_information.address_line1 %></td>
        <td><%= client_information.address_line2 %></td>
        <td><%= client_information.address_line3 %></td>
        <td><%= client_information.address_line4 %></td>
        <td><%= client_information.postal %></td>
        <td><%= client_information.external_trading_account %></td>
        <td><%= client_information.cgt_individual %></td>
        <td><%= link_to 'Show', client_information %></td>
        <td><%= link_to 'Edit', edit_client_information_path(client_information) %></td>
        <td><%= link_to 'Destroy', client_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Information', new_client_information_path %>

app/views/client_informations/new.html.erb
<h1>New Client Information</h1>

<%= render 'form', client_information: @client_information %>

<%= link_to 'Back', client_informations_path %>

app/views/client_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fund account:</strong>
  <%= @client_information.fund_account %>
</p>

<p>
  <strong>Fund name:</strong>
  <%= @client_information.fund_name %>
</p>

<p>
  <strong>Bda branch code:</strong>
  <%= @client_information.bda_branch_code %>
</p>

<p>
  <strong>Take on date:</strong>
  <%= @client_information.take_on_date %>
</p>

<p>
  <strong>Client title:</strong>
  <%= @client_information.client_title %>
</p>

<p>
  <strong>Client initials:</strong>
  <%= @client_information.client_initials %>
</p>

<p>
  <strong>First name:</strong>
  <%= @client_information.first_name %>
</p>

<p>
  <strong>Client surname:</strong>
  <%= @client_information.client_surname %>
</p>

<p>
  <strong>Idno:</strong>
  <%= @client_information.idno %>
</p>

<p>
  <strong>Tel no 1:</strong>
  <%= @client_information.tel_no_1 %>
</p>

<p>
  <strong>Tel no 2:</strong>
  <%= @client_information.tel_no_2 %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @client_information.email_address %>
</p>

<p>
  <strong>Tax no:</strong>
  <%= @client_information.tax_no %>
</p>

<p>
  <strong>Vat no:</strong>
  <%= @client_information.vat_no %>
</p>

<p>
  <strong>Address line1:</strong>
  <%= @client_information.address_line1 %>
</p>

<p>
  <strong>Address line2:</strong>
  <%= @client_information.address_line2 %>
</p>

<p>
  <strong>Address line3:</strong>
  <%= @client_information.address_line3 %>
</p>

<p>
  <strong>Address line4:</strong>
  <%= @client_information.address_line4 %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @client_information.postal %>
</p>

<p>
  <strong>External trading account:</strong>
  <%= @client_information.external_trading_account %>
</p>

<p>
  <strong>Cgt individual:</strong>
  <%= @client_information.cgt_individual %>
</p>

<%= link_to 'Edit', edit_client_information_path(@client_information) %> |
<%= link_to 'Back', client_informations_path %>