config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'
  resources :profiles
  resources :agc_definition_tables
  devise_for :users
  resources :iress_portfolio_cash_details
  resources :year_to_dates
  resources :month_to_dates 
  resources :profit_and_losses do
    collection do
      get :get_pnl_details
      post :get_profit_and_loss_by_fund_account
    end
  end
  resources :turnovers
  resources :prices
  resources :portfolio_valuations do
    collection do
    post :get_portfoilio_valuation_details  
    post :get_report_graph_portfolio_valuations
    get :get_portfoilio_graph_details
    end
  end
  resources :instruments
  resources :instrument_margin_levels
  resources :fx_rates
  resources :deal_transactions
  resources :client_informations
  resources :client_category_to_instruments
  resources :client_categories
  resources :cash_flow_types
  resources :cash_flow_sub_types
  resources :financial_transactions do
    collection do 
      post :get_ft_by_fund_account_and_date
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    self.table_name = "peregrine.instrument"
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:valuation_date, :exchange, :instrument_code, :currency_code, :isin, :sedol, :instrument_name, :sector, :industry)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<%= form_with(model: instrument, local: true) do |form| %>
  <% if instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valuation_date %>
    <%= form.datetime_select :valuation_date %>
  </div>

  <div class="field">
    <%= form.label :exchange %>
    <%= form.text_field :exchange %>
  </div>

  <div class="field">
    <%= form.label :instrument_code %>
    <%= form.text_field :instrument_code %>
  </div>

  <div class="field">
    <%= form.label :currency_code %>
    <%= form.text_field :currency_code %>
  </div>

  <div class="field">
    <%= form.label :isin %>
    <%= form.text_field :isin %>
  </div>

  <div class="field">
    <%= form.label :sedol %>
    <%= form.text_field :sedol %>
  </div>

  <div class="field">
    <%= form.label :instrument_name %>
    <%= form.text_field :instrument_name %>
  </div>

  <div class="field">
    <%= form.label :sector %>
    <%= form.text_field :sector %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Editing Instrument</h1>

<%= render 'form', instrument: @instrument %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instruments</h1>

<table>
  <thead>
    <tr>
      <th>Valuation date</th>
      <th>Exchange</th>
      <th>Instrument code</th>
      <th>Currency code</th>
      <th>Isin</th>
      <th>Sedol</th>
      <th>Instrument name</th>
      <th>Sector</th>
      <th>Industry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.valuation_date %></td>
        <td><%= instrument.exchange %></td>
        <td><%= instrument.instrument_code %></td>
        <td><%= instrument.currency_code %></td>
        <td><%= instrument.isin %></td>
        <td><%= instrument.sedol %></td>
        <td><%= instrument.instrument_name %></td>
        <td><%= instrument.sector %></td>
        <td><%= instrument.industry %></td>
        <td><%= link_to 'Show', instrument %></td>
        <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New Instrument</h1>

<%= render 'form', instrument: @instrument %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valuation date:</strong>
  <%= @instrument.valuation_date %>
</p>

<p>
  <strong>Exchange:</strong>
  <%= @instrument.exchange %>
</p>

<p>
  <strong>Instrument code:</strong>
  <%= @instrument.instrument_code %>
</p>

<p>
  <strong>Currency code:</strong>
  <%= @instrument.currency_code %>
</p>

<p>
  <strong>Isin:</strong>
  <%= @instrument.isin %>
</p>

<p>
  <strong>Sedol:</strong>
  <%= @instrument.sedol %>
</p>

<p>
  <strong>Instrument name:</strong>
  <%= @instrument.instrument_name %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @instrument.sector %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @instrument.industry %>
</p>

<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>